/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author gabri
 */
public class FrmAlimentos extends javax.swing.JFrame {

    /**
     * Creates new form FrmAlimentos
     */
    public FrmAlimentos() {
        initComponents();
        loadFoodData();
    }
    
    public void loadFoodData() {
        DBController db = new DBController("fitpro.db");
        
        try {
            db.connect();
            ResultSet rset = db.getFood();
            DefaultTableModel table = new DefaultTableModel(new String[]{"Nome", "Proteina (100g)", "Carboidrato (100g)", "Gordura (100g)", "Calorias (100g)"}, 0);
            
            while(rset.next()){
                table.addRow(new Object[]{rset.getString("name"), rset.getString("protein"), rset.getString("carbohydrate"), rset.getString("fat"), rset.getString("calorie")});
            }
            
            db.disconnect();
            
            jt_Foods.setModel(table);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_Main = new javax.swing.JPanel();
        jsp_Foods = new javax.swing.JScrollPane();
        jt_Foods = new javax.swing.JTable();
        jb_Return = new javax.swing.JButton();
        jb_AddFood = new javax.swing.JButton();
        jb_Refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jt_Foods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Alimento", "Proteina (100g)", "Carboidrato (100g)", "Gordura (100g)", "Caloria (100g)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jsp_Foods.setViewportView(jt_Foods);
        if (jt_Foods.getColumnModel().getColumnCount() > 0) {
            jt_Foods.getColumnModel().getColumn(0).setResizable(false);
            jt_Foods.getColumnModel().getColumn(1).setResizable(false);
            jt_Foods.getColumnModel().getColumn(2).setResizable(false);
            jt_Foods.getColumnModel().getColumn(3).setResizable(false);
        }

        jb_Return.setText("Voltar");
        jb_Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ReturnActionPerformed(evt);
            }
        });

        jb_AddFood.setText("Inserir Alimento");
        jb_AddFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AddFoodActionPerformed(evt);
            }
        });

        jb_Refresh.setText("Atualizar Tabela");
        jb_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_MainLayout = new javax.swing.GroupLayout(jp_Main);
        jp_Main.setLayout(jp_MainLayout);
        jp_MainLayout.setHorizontalGroup(
            jp_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_AddFood)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_Refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_Return)
                .addContainerGap())
            .addComponent(jsp_Foods, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        jp_MainLayout.setVerticalGroup(
            jp_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_MainLayout.createSequentialGroup()
                .addComponent(jsp_Foods, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_Return)
                    .addGroup(jp_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_AddFood)
                        .addComponent(jb_Refresh)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ReturnActionPerformed
        dispose();
    }//GEN-LAST:event_jb_ReturnActionPerformed

    private void jb_AddFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AddFoodActionPerformed
        FrmAddAlimento ft = new FrmAddAlimento();
        ft.setVisible(true);
    }//GEN-LAST:event_jb_AddFoodActionPerformed

    private void jb_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_RefreshActionPerformed
        loadFoodData();
    }//GEN-LAST:event_jb_RefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_AddFood;
    private javax.swing.JButton jb_Refresh;
    private javax.swing.JButton jb_Return;
    private javax.swing.JPanel jp_Main;
    private javax.swing.JScrollPane jsp_Foods;
    private javax.swing.JTable jt_Foods;
    // End of variables declaration//GEN-END:variables
}
