/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import javax.swing.*;

/**
 *
 * @author gabri
 */
public class FrmAddExercicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmAddExercicio
     */
    public FrmAddExercicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jp_Main = new javax.swing.JPanel();
        jp_Form = new javax.swing.JPanel();
        jl_Name = new javax.swing.JLabel();
        jtf_Name = new javax.swing.JTextField();
        jl_Intensity = new javax.swing.JLabel();
        jtf_Intensity = new javax.swing.JTextField();
        jl_Difficult = new javax.swing.JLabel();
        jtf_Difficult = new javax.swing.JTextField();
        jp_Areas = new javax.swing.JPanel();
        jcb_Upper = new javax.swing.JCheckBox();
        jcb_Core = new javax.swing.JCheckBox();
        jcb_Lower = new javax.swing.JCheckBox();
        jb_Return = new javax.swing.JButton();
        jb_AddWorkout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jp_Form.setBorder(javax.swing.BorderFactory.createTitledBorder("Adição de Exercicos"));

        jl_Name.setText("Nome");

        jl_Intensity.setText("Intensidade");

        jl_Difficult.setText("Dificuldade");

        jp_Areas.setBorder(javax.swing.BorderFactory.createTitledBorder("Área de Ativação"));

        buttonGroup1.add(jcb_Upper);
        jcb_Upper.setText("Superior");

        buttonGroup1.add(jcb_Core);
        jcb_Core.setText("Core");

        buttonGroup1.add(jcb_Lower);
        jcb_Lower.setText("Inferior");

        javax.swing.GroupLayout jp_AreasLayout = new javax.swing.GroupLayout(jp_Areas);
        jp_Areas.setLayout(jp_AreasLayout);
        jp_AreasLayout.setHorizontalGroup(
            jp_AreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_AreasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_AreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_Upper)
                    .addComponent(jcb_Core)
                    .addComponent(jcb_Lower))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jp_AreasLayout.setVerticalGroup(
            jp_AreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_AreasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcb_Upper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_Core)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_Lower)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_FormLayout = new javax.swing.GroupLayout(jp_Form);
        jp_Form.setLayout(jp_FormLayout);
        jp_FormLayout.setHorizontalGroup(
            jp_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_FormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_Name)
                    .addComponent(jl_Difficult)
                    .addComponent(jl_Intensity)
                    .addComponent(jp_Areas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_Name)
                    .addComponent(jtf_Intensity)
                    .addComponent(jtf_Difficult, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_FormLayout.setVerticalGroup(
            jp_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_FormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_Intensity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_Intensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jl_Difficult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_Difficult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jp_Areas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jb_Return.setText("Voltar");
        jb_Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ReturnActionPerformed(evt);
            }
        });

        jb_AddWorkout.setText("Adicionar");
        jb_AddWorkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AddWorkoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_MainLayout = new javax.swing.GroupLayout(jp_Main);
        jp_Main.setLayout(jp_MainLayout);
        jp_MainLayout.setHorizontalGroup(
            jp_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_MainLayout.createSequentialGroup()
                        .addComponent(jp_Form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jp_MainLayout.createSequentialGroup()
                        .addComponent(jb_AddWorkout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_Return)))
                .addContainerGap())
        );
        jp_MainLayout.setVerticalGroup(
            jp_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_Form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_AddWorkout)
                    .addComponent(jb_Return))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ReturnActionPerformed
        dispose();
    }//GEN-LAST:event_jb_ReturnActionPerformed

    private void jb_AddWorkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AddWorkoutActionPerformed
        DBController db = new DBController("fitpro.db");
        
        String name = jtf_Name.getText(), intensity = jtf_Intensity.getText(), difficult = jtf_Difficult.getText(), area = "";
        
        if(jcb_Upper.isSelected()){
            area = "Upper";
        }
        if(jcb_Core.isSelected()){
            area = "Core";
        }
        if(jcb_Lower.isSelected()){
            area = "Lower";
        }
        
        try {
            if(name.equals("") || intensity.equals("") || difficult.equals("") || area.equals("")){
                JOptionPane.showMessageDialog(this, "Falta Informações Para O Cadastro !");
            } else {
                db.connect();
                db.setWorkout(name, intensity, difficult, area);
                db.disconnect();
                JOptionPane.showMessageDialog(this, "Exercício Cadastrado Com Sucesso !");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jb_AddWorkoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAddExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAddExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAddExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAddExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAddExercicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jb_AddWorkout;
    private javax.swing.JButton jb_Return;
    private javax.swing.JCheckBox jcb_Core;
    private javax.swing.JCheckBox jcb_Lower;
    private javax.swing.JCheckBox jcb_Upper;
    private javax.swing.JLabel jl_Difficult;
    private javax.swing.JLabel jl_Intensity;
    private javax.swing.JLabel jl_Name;
    private javax.swing.JPanel jp_Areas;
    private javax.swing.JPanel jp_Form;
    private javax.swing.JPanel jp_Main;
    private javax.swing.JTextField jtf_Difficult;
    private javax.swing.JTextField jtf_Intensity;
    private javax.swing.JTextField jtf_Name;
    // End of variables declaration//GEN-END:variables
}
