/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author gabri
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_Main = new javax.swing.JPanel();
        jp_Logo = new javax.swing.JPanel();
        jl_Logo = new javax.swing.JLabel();
        jp_Workouts = new javax.swing.JPanel();
        jl_WorkoutsDesc = new javax.swing.JLabel();
        jb_GoToWorkouts = new javax.swing.JButton();
        jp_Foods = new javax.swing.JPanel();
        jl_FoodsDesc = new javax.swing.JLabel();
        jb_GoToFoods = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fit Pro");

        jp_Main.setPreferredSize(new java.awt.Dimension(500, 500));

        jp_Logo.setBackground(new java.awt.Color(255, 123, 37));
        jp_Logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(114, 114, 114), 2));

        jl_Logo.setFont(new java.awt.Font("Georgia", 3, 84)); // NOI18N
        jl_Logo.setForeground(new java.awt.Color(229, 229, 229));
        jl_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Logo.setText("FitPRO");

        javax.swing.GroupLayout jp_LogoLayout = new javax.swing.GroupLayout(jp_Logo);
        jp_Logo.setLayout(jp_LogoLayout);
        jp_LogoLayout.setHorizontalGroup(
            jp_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_LogoLayout.setVerticalGroup(
            jp_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        jp_Workouts.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Treinos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jl_WorkoutsDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_WorkoutsDesc.setText("Área destinada a criação de treinos personalizados.");
        jl_WorkoutsDesc.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));

        jb_GoToWorkouts.setText("Exibir");
        jb_GoToWorkouts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_GoToWorkoutsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_WorkoutsLayout = new javax.swing.GroupLayout(jp_Workouts);
        jp_Workouts.setLayout(jp_WorkoutsLayout);
        jp_WorkoutsLayout.setHorizontalGroup(
            jp_WorkoutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_WorkoutsLayout.createSequentialGroup()
                .addComponent(jl_WorkoutsDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_GoToWorkouts)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_WorkoutsLayout.setVerticalGroup(
            jp_WorkoutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_WorkoutsLayout.createSequentialGroup()
                .addGroup(jp_WorkoutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_WorkoutsDesc)
                    .addComponent(jb_GoToWorkouts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_Foods.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alimentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jl_FoodsDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_FoodsDesc.setText("Área destinada a descrição nutricional de alimentos.");
        jl_FoodsDesc.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));

        jb_GoToFoods.setText("Exibir");
        jb_GoToFoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_GoToFoodsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_FoodsLayout = new javax.swing.GroupLayout(jp_Foods);
        jp_Foods.setLayout(jp_FoodsLayout);
        jp_FoodsLayout.setHorizontalGroup(
            jp_FoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_FoodsLayout.createSequentialGroup()
                .addComponent(jl_FoodsDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_GoToFoods)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_FoodsLayout.setVerticalGroup(
            jp_FoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_FoodsLayout.createSequentialGroup()
                .addGroup(jp_FoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_FoodsDesc)
                    .addComponent(jb_GoToFoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_MainLayout = new javax.swing.GroupLayout(jp_Main);
        jp_Main.setLayout(jp_MainLayout);
        jp_MainLayout.setHorizontalGroup(
            jp_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_Workouts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_Foods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_MainLayout.setVerticalGroup(
            jp_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_Workouts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_Foods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_GoToWorkoutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_GoToWorkoutsActionPerformed
        FrmTreinos ft = new FrmTreinos();
        ft.setVisible(true);
    }//GEN-LAST:event_jb_GoToWorkoutsActionPerformed

    private void jb_GoToFoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_GoToFoodsActionPerformed
        FrmAlimentos fa = new FrmAlimentos();
        fa.setVisible(true);
    }//GEN-LAST:event_jb_GoToFoodsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_GoToFoods;
    private javax.swing.JButton jb_GoToWorkouts;
    private javax.swing.JLabel jl_FoodsDesc;
    private javax.swing.JLabel jl_Logo;
    private javax.swing.JLabel jl_WorkoutsDesc;
    private javax.swing.JPanel jp_Foods;
    private javax.swing.JPanel jp_Logo;
    private javax.swing.JPanel jp_Main;
    private javax.swing.JPanel jp_Workouts;
    // End of variables declaration//GEN-END:variables
}